skepticalsciencewebsite/faq/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from faq.views import FAQView

urlpatterns = [url(r'^$', FAQView.as_view(), name='faq')]

skepticalsciencewebsite/skepticalsciencewebsite/urls.py
from django.conf.urls import url, include
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.views.generic import TemplateView
# from django.conf.urls.static import static
# from skepticalsciencewebsite import settings


# internationalization http://www.marinamele.com/taskbuster-django-tutorial/internationalization-localization-languages-time-zones

urlpatterns = [
    url(r'^select2/', include('django_select2.urls')),
]  # + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('customuser.urls')),
    # https://github.com/incuna/django-registration/blob/master/registration/urls.py under accounts
    url(r'^accounts/', include('registration.backends.hmac.urls')),
    url(r'^faq/', include('faq.urls')),
    url(r'^checkout/', include('custompayment.urls')),
    url('^checkout/', include('payments.urls')),
    url(r'^publications/', include('publications.urls')),
    url(r'^invoice/', include('pdfinvoce.urls')),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name="index"),
    url(r'^legal_notices$', TemplateView.as_view(template_name='legal_notices.html'), name="legal_notices"),
    url(r'^tos$', TemplateView.as_view(template_name='tos.html'), name="tos"),
    url(r'^selling_contract$', TemplateView.as_view(template_name='selling_contract.html'), name="selling_contract"),
    prefix_default_language=False,
)

skepticalsciencewebsite/faq/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
# Create your models here.


class Topic(models.Model):

    name = models.CharField(verbose_name=_("Topic"), max_length=255, unique=True)
    slug = models.SlugField(verbose_name=_("Slug"))

    def __str__(self):
        return self.name


class QandA(models.Model):

    topic = models.ForeignKey(Topic)
    question = models.CharField(verbose_name=_("Question"), max_length=255, unique=True)
    answer = models.CharField(verbose_name=_("Answer"), max_length=1024, unique=True)
    slug = models.SlugField(verbose_name=_("Slug"))

    def __str__(self):
        return self.question

skepticalsciencewebsite/faq/views.py
from django.views import generic
from faq.models import Topic
from faq.models import QandA


class FAQView(generic.ListView):
    template_name = 'faq/faq.html'
    context_object_name = 'topic_list'

    def get_queryset(self):
        """Return list of FAQs"""
        return Topic.objects.all()

skepticalsciencewebsite/faq/templates/faq/faq.html
{% extends "base.html" %}
{% load i18n %}

{% load bootstrap3 %}


{% block content %}
    <h1>{% trans "F.A.Q." %}</h1>
    {% if topic_list %}
    <ol>
        {% for topic in topic_list %}
            <h4><li><a href="#{{ topic.slug }}">{{ topic.name }}</a></li></h4>
            <ul>
            {% for question in topic.qanda_set.all %}
                <li><a href="#{{ question.slug }}">{{ question.question }}</a></li>
            {% endfor %}
            </ul>
        {% endfor %}
    </ol>
    {% for topic in topic_list %}
        <div>
            <a id="{{ topic.slug }}"><h2>{{ topic.name }}</h2></a>

            <ul>
                {% for question in topic.qanda_set.all %}
                    <li><a id="{{ question.slug }}">{{ question.question }}</a> <br /> {{ question.answer }}</li>
                {% endfor %}
            </ul>
        </div>
    {% endfor %}
    {% else %}
        <p>No topics have been created.</p>
    {% endif %}
{% endblock content%}