skepticalsciencewebsite/faq/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from faq.views import FAQView

urlpatterns = [url(r'^$', FAQView.as_view(), name='faq')]

skepticalsciencewebsite/publications/urls.py
from django.conf.urls import url
from publications.views import (PublicationCreate, PublicationUpdate, PublicationCorrectionUpdate,
                                PublicationAbortUpdate, download, PublicationTableView, PublicationToReviewTableView,
                                PublicationInReviewTableView, PublicationToEvaluateTableView, PublicationDetailView,
                                PublicationOwnedTableView, become_reviewer_view, leave_reviewer_view,
                                CommentDetailView, PublicationYouReviewTableView)

urlpatterns = [url(r'^new_publication/$', PublicationCreate.as_view(), name="create_publication"),
               url(r'^edit_publication/(?P<pk>\d+)/$', PublicationUpdate.as_view(), name="update_publication"),
               url(r'^correct_publication/(?P<pk>\d+)/$', PublicationCorrectionUpdate.as_view(),
                   name="correct_publication"),
               url(r'^abort_publication/(?P<pk>\d+)/$', PublicationAbortUpdate.as_view(),
                   name="abort_publication"),
               url(r'^download_publication/(?P<field_name>\w+)/(?P<publication_id>\d+)/$', download,
                   name="download_publication"),
               url(r'^publication_list/$', PublicationTableView.as_view(), name="publication_list"),
               url(r'^publication_to_review/$', PublicationToReviewTableView.as_view(),name="publication_to_review"),
               url(r'^publication_in_review/$', PublicationInReviewTableView.as_view(), name="publication_in_review"),
               url(r'^publication_you_review/$', PublicationYouReviewTableView.as_view(), name="publication_you_review"),
               url(r'^publication_to_evaluate/$', PublicationToEvaluateTableView.as_view(),
                   name="publication_to_evaluate"),
               url(r'^publication_owned/$', PublicationOwnedTableView.as_view(), name="publication_owned"),
               url(r'publication_detail/(?P<pk>\d+)/$', PublicationDetailView.as_view(),
                   name="publication_view"),
               url(r'become_reviewer/(?P<publication_id>\d+)/$', become_reviewer_view, name="become_reviewer"),
               url(r'leave_reviewer/(?P<publication_id>\d+)/$', leave_reviewer_view, name="leave_reviewer"),
               url(r'^comment_detail/(?P<pk>\d+)/$', CommentDetailView.as_view(),
                   name="comment_view")
]

skepticalsciencewebsite/skepticalsciencewebsite/urls.py
from django.conf.urls import url, include
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.views.generic import TemplateView
# from django.conf.urls.static import static
# from skepticalsciencewebsite import settings


# internationalization http://www.marinamele.com/taskbuster-django-tutorial/internationalization-localization-languages-time-zones

urlpatterns = [
    url(r'^select2/', include('django_select2.urls')),
]  # + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('customuser.urls')),
    # https://github.com/incuna/django-registration/blob/master/registration/urls.py under accounts
    url(r'^accounts/', include('registration.backends.hmac.urls')),
    url(r'^faq/', include('faq.urls')),
    url(r'^checkout/', include('custompayment.urls')),
    url('^checkout/', include('payments.urls')),
    url(r'^publications/', include('publications.urls')),
    url(r'^invoice/', include('pdfinvoce.urls')),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name="index"),
    url(r'^legal_notices$', TemplateView.as_view(template_name='legal_notices.html'), name="legal_notices"),
    url(r'^tos$', TemplateView.as_view(template_name='tos.html'), name="tos"),
    url(r'^selling_contract$', TemplateView.as_view(template_name='selling_contract.html'), name="selling_contract"),
    prefix_default_language=False,
)

skepticalsciencewebsite/publications/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.core.exceptions import ValidationError
# from simple_history.models import HistoricalRecords
from sciences.models import Science
from customuser.models import MinMaxFloat
from publications.constants import *

sendfile_storage = FileSystemStorage(location=settings.SENDFILE_ROOT, base_url=settings.SENDFILE_URL)
# Create your models here.


class Licence(models.Model):
    """
    Legal licence Model
    """
    short_name = models.CharField(max_length=64, blank=False, verbose_name=_("Short name"))
    full_name = models.CharField(max_length=255, blank=False, verbose_name=_("Full name"))
    url = models.URLField(max_length=255, blank=False, verbose_name=_("URL"))

    def __str__(self):
        return self.short_name


class Publication(models.Model):
    """
    Publication Model. Need the author
    """
    # other author problem ? What to do if no account, if account ?
    editor = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_('Editor'))
    # create the publication before paying for
    creation_date = models.DateTimeField(auto_now_add=True, verbose_name=_('Date created'))
    payment_date = models.DateTimeField(null=True, blank=True, default=None, verbose_name=_('Payment date'))
    validation_date = models.DateTimeField(null=True, blank=True, default=None, verbose_name=_('Validation date'))
    sciences = models.ManyToManyField(Science, blank=True, symmetrical=False, verbose_name=_("Sciences"))
    title = models.CharField(max_length=255, blank=False, verbose_name=_("Title"))
    publication_score = MinMaxFloat(min_value=0.0, max_value=10.0, default=None, null=True, blank=True,
                                    verbose_name=_("Publication score"))
    estimated_impact_factor = MinMaxFloat(min_value=0.0, max_value=1000.0, default=None, null=True, blank=True,
                                          verbose_name=_("Estimated impact factor"))
    # authors ????
    first_author = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='first_author', verbose_name=_("First author"))
    authors = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name='authors', verbose_name=_("Authors"))
    last_author = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, related_name='last_author',
                                    verbose_name=_("Last author"))
    # the pdf file at the creation
    pdf_creation = models.FileField(upload_to="pdf_creation/%Y/%m/%d", blank=True, storage=sendfile_storage,
                                    verbose_name=_("Publication draft (PDF)"))
    source_creation = models.FileField(upload_to="source_creation/%Y/%m/%d", blank=True, storage=sendfile_storage,
                                       verbose_name=_("Publication draft (sources)"))
    pdf_final = models.FileField(upload_to="pdf_final/%Y/%m/%d", null=True, blank=True, storage=sendfile_storage,
                                 verbose_name=_("Publication final (pdf)"))
    source_final = models.FileField(upload_to="source_final/%Y/%m/%d", null=True, blank=True, storage=sendfile_storage,
                                    verbose_name=_("Publication final (sources)"))
    resume = models.CharField(max_length=1024, blank=False, verbose_name=_("Resume"))
    status = models.IntegerField(choices=PUBLICATION_STATUS, db_index=True, default=1, verbose_name=_('Status'))
    update_status_date = models.DateTimeField(auto_now_add=True, verbose_name=_('Update status date'))
    # or just resume ?
    # tags = models.ManyToManyField(KeyWord, blank= False, symmetrical=False, verbose_name=_("Keywords"))
    licence = models.ForeignKey(Licence, verbose_name=_("Licence"))
    doi = models.CharField(max_length=255, blank=True, verbose_name=_("DOI"))
    # history = HistoricalRecords()

    @property
    def get_all_authors(self):
        authors = [self.first_author] + [author for author in self.authors.all()] + \
                  [author for author in [self.last_author] if author is not None]
        return authors

    def clean(self, *args, **kwargs):
        super(Publication, self).clean(*args, **kwargs)
        if not self.pdf_creation or not self.source_creation:
            raise ValidationError(_("You must have publications drafts files"))

    def __str__(self):
        return self.title


class EstimatedImpactFactor(models.Model):
    """
    EstimatedImpactFactor Model
    """
    # must be in researcher group and have a related sciences
    estimator = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_('Estimator'))
    publication = models.ForeignKey(Publication, verbose_name=_('Publication'))
    estimated_impact_factor = MinMaxFloat(min_value=0.0, max_value=1000.0, verbose_name=_("Estimated impact factor"))

    def __str__(self):
        return self.estimator.get_full_name()

    class Meta:
        unique_together = ('estimator', 'publication')


class Reviewer(models.Model):
    """
    Reviewer Model
    """
    scientist = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_("Reviewer"))
    publication = models.ForeignKey(Publication, verbose_name=_("Publication"))
    actif = models.BooleanField(default=True, verbose_name=_("Activated"))
    # history = HistoricalRecords()

    class Meta:
        unique_together = ('scientist', 'publication')

    def __str__(self):
        return self.scientist.get_full_name()


class Comment(models.Model):
    """
    Comment model
    """
    publication = models.ForeignKey(Publication, verbose_name=_("Publication"))
    author = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_("Author"))
    # fake pseudo when reviewer must be reviewer (fake pseudo given automatically between: Reviewer, Scientist, Skeptic)
    author_fake_pseudo = models.CharField(max_length=100, default=None, blank=True, verbose_name=_('Alias'))
    creation_date = models.DateTimeField(auto_now_add=True, verbose_name=_('Date created'))
    comment_type = models.IntegerField(choices=COMMENT_ON, db_index=True, verbose_name=_("Comment type"))
    seriousness = models.IntegerField(choices=SERIOUSNESS_STATUS, db_index=True, blank=True, null=True,
                                      verbose_name=_("Seriousness"))
    content = models.CharField(max_length=8192, blank=False, verbose_name=_("Publication comment"))
    title = models.CharField(max_length=255, blank=False, verbose_name=_("Title"))
    validated = models.IntegerField(choices=VALIDATION_STATUS, default=2, verbose_name=_("Validation"))
    corrected = models.BooleanField(default=False, verbose_name=_("Corrected"))
    corrected_date = models.DateTimeField(null=True, blank=True, default=None, verbose_name=_('Date corrected'))
    licence = models.ForeignKey(Licence, verbose_name=_("License"))

    def __str__(self):
        return self.title


class CommentReview(models.Model):
    """
     when done must check if every other reviewer have already done it
    """
    comment = models.ForeignKey(Comment, verbose_name=_("Comment"))
    reviewer = models.ForeignKey(Reviewer, verbose_name=_("Reviewer"))
    creation_date = models.DateTimeField(auto_now_add=True, verbose_name=_('Date created'))
    seriousness = models.IntegerField(choices=SERIOUSNESS_STATUS, db_index=True, verbose_name=_("Seriousness"))
    valid = models.BooleanField(default=False, verbose_name=_("Valid"))
    reason_validation = models.CharField(max_length=8192, blank=False, verbose_name=_("Reason of (in)validation"))
    corrected_date = models.DateTimeField(null=True, blank=True, default=None, verbose_name=_('Date Corrected'))
    corrected = models.BooleanField(default=False, verbose_name=_("Corrected"))
    reason_correction = models.CharField(max_length=8192, blank=False, verbose_name=_("Reason of (in)correction"))

    def __str__(self):
        return self.comment.title

    class Meta:
        unique_together = ('reviewer', 'comment')
    # def clean(self):
    #     to put in the form valid
    #     if self.reviewer.publication != self.comment.publication:
    #         raise ValidationError('You are not a reviewer of this publication. Therefor You cannot rate this comment')

skepticalsciencewebsite/publications/templates/publications/comment_detail.html
{% extends "base.html" %}
{% load i18n %}

{% load bootstrap3 %}
{% load crispy_forms_tags %}

{% block content %}
    <h1>{% trans "Comment" %}: {{ comment_detail.title }}</h1>

    <div class="row">
        <div class="col-md-8">
            <div class="bs-component">
                <blockquote>
                    <p>{{ comment_detail.content|linebreaks }}</p>
                    <small>{{ comment_detail.author_fake_pseudo|default:comment_detail.author }}</small>
                </blockquote>
            </div>
        </div>
        <div class="col-md-4">
            <h5><strong>{% trans "Date Created" %}</strong></h5>
            <p class="text-indent">{{ comment_detail.creation_date }}</p>
            <h5><strong>{% trans "Comment on" %}</strong></h5>
            <p class="text-indent">{{ comment_detail.get_comment_type_display }}</p>
            <h5><strong>{% trans "License" %}</strong></h5>
            <p class="text-indent">{{ comment_detail.licence }}</p>
            <h5><strong>{% trans "Status" %}</strong></h5>
            <p class="text-indent">{{ comment_detail.get_validated_display }}</p>
            {% if comment_detail.validated == constants.VALIDATE %}
                <h5><strong>{% trans "Seriousness" %}</strong></h5>
                <p class="text-indent">{{ comment_detail.get_seriousness_display }}</p>
                <h5><strong>{% trans "Corrected" %}</strong></h5>
                <p class="text-indent">{{ comment_detail.corrected|yesno|capfirst }}</p>
            {% endif %}
        </div>
    </div>

    <hr>
    <h2>{% trans "Evaluations" %}:</h2>
    {% for review in reviews %}
        {% if review.valid %}
            {% if review.corrected %}
                <div class="panel panel-success">
            {% else %}
                <div class="panel panel-warning">
            {% endif %}
        {% else %}
            <div class="panel panel-default">
        {% endif %}
            <div class="panel-body">
                <div class="panel-title pull-left">
                    {% trans "Reason for " %} {{ review.valid|yesno:"validation,invalidation" }}:
                </div>
                <div class="panel-title pull-right">
                    {{ review.creation_date }}
                </div>
                <div class="clearfix"></div>
                <br>
                {{ review.reason_validation|linebreaks }}
                 <div class="panel-title pull-right">
                    {% trans "Seriousness" %}: {{ review.get_seriousness_display|lower }}
                </div>
                <div class="clearfix"></div>
                {% if review.reason_correction != "" %}
                    <hr>
                    <div class="panel-title pull-left">
                        {% trans "Reason for " %} {{ review.corrected|yesno:"correction,incorrection" }}:
                    </div>
                    <div class="panel-title pull-right">
                        {{ review.corrected_date }}
                    </div>
                    <div class="clearfix"></div>
                    <br>
                    {{ review.reason_correction|linebreaks }}
                {% endif %}
            </div>
        </div>
    {% empty %}
        {% trans "No evaluations yet" %}
    {% endfor %}

    <!-- show only at the good times  -->
    {% if review_state == "to_review_validation" and publication_status >= constants.PEER_REVIEW %}
        <hr>
        <h2>{% trans "Is this comment valid" %} ?</h2>
        {% crispy form_review_validation %}
        {{ form.media.js }}
    {% elif review_state == "to_review_correction" and publication_status == VALIDATION %}
        <hr>
        <h2>{% trans "Is this comment corrected" %} ?</h2>
        {% crispy correction %}
        {{ form.media.js }}
    {% endif %}

{% endblock %}

skepticalsciencewebsite/publications/templates/publications/publication_correct_form.html
{% extends "base.html" %}
{% load i18n %}

{% load bootstrap3 %}
{% load crispy_forms_tags %}

{% if user.id == publication.editor.id and publication.status == constants.WAITING_PAYMENT %}
    {% block content %}
        <h1>{% trans name %}</h1>
        {% crispy form %}
        {{ form.media.js }}
    {% endblock %}
{% endif %}

skepticalsciencewebsite/publications/templates/publications/publication_detail.html
{% extends "base.html" %}
{% load i18n %}

{% load bootstrap3 %}
{% load crispy_forms_tags %}


{% block content %}
    <h1>{% trans "Publication" %}: {{ publication_detail.title }}</h1>

    <!-- different with the status of the publication and if there is still validated comments -->
    <div class="alert alert-dismissible {{ alert.class }}">
        <button class="close" type="button" data-dismiss="alert">x</button>
        <h4>{{ alert.title }}</h4>
        <p>{{ alert.message }}</p>
    </div>

    <div class="row">
        <div class="col-md-8">
            <div class="bs-component">
                <blockquote>
                    <p>{{ publication_detail.resume|linebreaks }}</p>
                    <small>{{ publication_detail.editor.get_full_name }}</small>
                </blockquote>
                <!-- and good publication in evaluation and user in phd-->
                {% if user.phd and not user in publication_detail.get_all_authors %}
                    {% if perms.publications.add_reviewer and perms.publications.change_reviewer and reviewer_registration %}
                        {% if is_reviewer %}
                            <p><a href="{% url 'leave_reviewer' object.pk %}"> {% trans "Leave the reviewers" %}</a></p>
                        {% else %}
                            <p><a href="{% url 'become_reviewer' object.pk %}"> {% trans "Join the reviewers" %}</a></p>
                        {% endif %}
                    {% endif %}
                    {% if perms.publications.add_estimated_impact_factor and publication_detail.status == constants.EVALUATION %}
                        {% if not evaluated %}
                            <h5><strong> {% trans "Evaluate" %} </strong></h5>
                            {% crispy form_eif %}
                        {% else %}
                            {% trans "You already have evaluated this publication" %}.
                        {% endif %}
                    {% endif %}
                {% endif %}
                {% if perms.publications.change_publication and publication_detail.status == constants.CORRECTION and is_editor %}
                    <!-- to do as a link-->
                    <p><a href="{% url 'correct_publication' object.pk %}">{% trans "Correct " %}</a>
                    {% trans "or " %}
                    <a href="{% url 'abort_publication' object.pk %}">{% trans "abort " %}</a>
                    {% trans "this publication" %}.</p>
                {% elif perms.publications.change_publication and publication_detail.status == constants.WAITING_PAYMENT and is_editor %}
                    <p><a href="{% url 'update_publication' object.pk %}">{% trans "Edit " %}</a>
                    {% trans "or " %}
                    <a href="{% url 'create_order' name=order sku=object.pk %}">{% trans "pay to submit " %}</a>
                    {% trans "the publication" %}.
                    </p>
                    <p class="text-danger">
                        {% blocktrans %}
                            Once payment has been made the publication is submitted for peer review and
                             cannot be edited until the correction process is over.
                        {% endblocktrans %}
                    </p>
                {% endif %}

                <!-- participate at the rewiew in add_peer, user scientist with phd and not in author-->
            </div>
        </div>
        <div class="col-md-4">
            <h5><strong>{% trans "Date Created" %}</strong></h5>
            <p class="text-indent">{{ publication_detail.creation_date }}</p>
            <h5><strong>{% trans "Sciences" %}</strong></h5>
            <p class="text-indent">{% for science in publication_detail.sciences.all %}
                    {% if forloop.last %}
                        {{ science }}
                    {% else %}
                        {{ science }},
                    {% endif %}
                {% endfor %}</p>
            <h5><strong>{% trans "Authors" %}</strong></h5>
            <p class="text-indent">
                {% for author in publication_detail.get_all_authors %}
                    {% if forloop.last %}
                        {{ author.get_full_name }}
                    {% else %}
                        {{ author.get_full_name }},
                    {% endif %}
                {% endfor %}</p>
            <h5><strong>{% trans "Status" %}</strong></h5>
            <p class="text-indent">{{ publication_detail.get_status_display }}</p>
            <h5><strong>{% trans "Downloads" %}</strong></h5>
            <p class="text-indent">
                <a href="{% url 'download_publication' 'pdf_creation' object.pk %}">{% trans "PDF first draft" %}</a>
            </p>
            <p class="text-indent">
                <a href="{% url 'download_publication' 'source_creation' object.pk %}">{% trans "Source first draft" %}</a>
            </p>
            {% if publication_detail.status >= constants.VALIDATION %}
                <p class="text-indent">
                    <a href="{% url 'download_publication' 'pdf_final' object.pk %}">{% trans "PDF final version" %}</a>
                </p>
                <p class="text-indent">
                    <a href="{% url 'download_publication' 'source_final' object.pk %}">{% trans "Source final version" %}</a>
                </p>
                <h5><strong>{% trans "Publication score" %}</strong></h5>
                <p class="text-indent">{{ publication_detail.publication_score }}</p>
            {% endif %}
            {% if publication_detail.status >= constants.PUBLISHED %}
                <h5><strong>{% trans "Estimated impact factor" %}</strong></h5>
                <p class="text-indent">{{ publication_detail.estimated_impact_factor}}</p>
            {% endif %}
            <h5><strong>{% trans "License" %}</strong></h5>
            <p class="text-indent">{{ publication_detail.licence }}</p>
            <!--dropdown button with download-->
        </div>
    </div>


    <hr>
    <h2>{% trans "Comments" %} :</h2>
    {% for comment in comments %}
<!-- color faded not validate, validated blue, if publication has been corrected then if the comment is
corrected green, if not red, if comment after the validation and valid then orange-->
        {% if comment.validated == constants.DISMISS %}
            <div class="panel panel-default">
        {% elif comment.validated == constants.IN_PROGRESS %}
            <div class="panel panel-primary">
        {% elif comment.corrected %}
            <div class="panel panel-success">
        {% elif comment.comment_type == constants.FORM %}
            <div class="panel panel-info">
        {% elif publication_detail.status >= constants.EVALUATION %}
            <div class="panel panel-warning">
        {% else %}
            <div class="panel panel-danger">
        {% endif %}
            <div class="panel-heading">
                <div class="panel-title pull-left">
                    {{ comment.title }} {% trans " by "%} {{ comment.author_fake_pseudo|default:comment.author }}
                    {% trans " on the " %} {{ comment.get_comment_type_display|lower }}
                </div>
                <div class="panel-title pull-right">
                    {{ comment.get_seriousness_display|default:comment.get_validated_display}}
                </div>
                <div class="clearfix"></div>
            </div>

            <div class="panel-body">
                <p> {{ comment.content|linebreaks }}</p>
                <div class="panel-title pull-left">
                    {{ comment.licence }} ({{ comment.creation_date }})
                </div>
                <div class="panel-title pull-right">
                    <a href="{% url 'comment_view' comment.pk %}">{% trans "Comment evaluation" %}</a>
                </div>
            </div>
        </div>
    {% empty %}
        {% trans "No comments yet" %}
    {% endfor %}

    <hr>
    <h2>{% trans "Submit comment"%}: </h2>
    {% if user.is_authenticated and publication_detail.status >= constants.ADDING_PEER %}
        <p class="text-info">{% blocktrans %} A comment must describe only one error.
                                              If you spotted more than one, please write more than one comment.
                             {% endblocktrans %} </p>
        {% crispy form_comment %}
        {{ form.media.js }}
    {% elif user.is_authenticated %}
        <p class="text-info">{% trans "Only payed publications can receive comments." %}</p>
    {% endif %}

{% endblock %}

skepticalsciencewebsite/publications/templates/publications/publication_edit_form.html
{% extends "base.html" %}
{% load i18n %}

{% load bootstrap3 %}
{% load crispy_forms_tags %}

{% if user.id == publication.editor.id and publication.status == constants.CORRECTION %}
    {% block content %}
        <h1>{% trans name %}</h1>
        {% crispy form %}
        {{ form.media.js }}
    {% endblock %}
{% endif %}

skepticalsciencewebsite/publications/templates/publications/publication_form.html
{% extends "base.html" %}
{% load i18n %}

{% load bootstrap3 %}
{% load crispy_forms_tags %}

{% block content %}
    <h1>{% trans name %}</h1>
    {% crispy form %}
    {{ form.media.js }}
{% endblock %}

skepticalsciencewebsite/publications/templates/publications/publication_list.html
{% extends "base.html" %}
{% load i18n %}

{% load staticfiles %}
{% load bootstrap3 %}
{% load django_tables2 crispy_forms_tags %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/table2.css' %}" />
{% endblock %}

{% block content %}
    <h1>{% trans "Publications" %}</h1>
    {% crispy filter.form filter.form.helper %}
    {% render_table table "modifytable.html" %}
{% endblock %}

skepticalsciencewebsite/publications/templates/publications/publication_special_list.html
{% extends "base.html" %}
{% load i18n %}

{% load staticfiles %}
{% load bootstrap3 %}
{% load django_tables2 crispy_forms_tags %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/table2.css' %}" />
{% endblock %}

{% block content %}
    <h1>{% trans "Publications " %} {% trans name %}</h1>
    {% render_table table %}
{% endblock %}